"""created sentmail table

Revision ID: 157ae5e82dcb
Revises: da5ef4256d98
Create Date: 2019-03-29 18:27:59.846874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157ae5e82dcb'
down_revision = 'da5ef4256d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentmails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_user', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentmails_email_user'), 'sentmails', ['email_user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentmails_email_user'), table_name='sentmails')
    op.drop_table('sentmails')
    # ### end Alembic commands ###
