"""removed sentmails

Revision ID: 8628e9feac2f
Revises: 157ae5e82dcb
Create Date: 2019-04-02 00:01:25.596913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8628e9feac2f'
down_revision = '157ae5e82dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sentmails_email_user', table_name='sentmails')
    op.drop_table('sentmails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentmails',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email_user', sa.VARCHAR(length=64), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=200), nullable=True),
    sa.Column('body', sa.VARCHAR(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sentmails_email_user', 'sentmails', ['email_user'], unique=False)
    # ### end Alembic commands ###
